# Generated by Django 2.1.3 on 2018-11-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='Título')),
                ('url', models.SlugField(help_text='URL baseada no titulo', max_length=200, unique=True, verbose_name='URL')),
                ('data_publicacao', models.DateField(verbose_name='Data publicação')),
                ('conteudo', models.TextField(verbose_name='Conteudo da página')),
                ('autor', models.ManyToManyField(to='autor.Autor')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'db_table': 'artigo',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
